# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

parameters:
  action:
    type: enum
    enum: [build, scheduled]
    default: build


jobs:

  download-and-create-db:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: mkdir -p ./bin && curl -L https://github.com/jeremylong/Open-Vulnerability-Project/releases/download/v5.1.0/vulnz-5.1.0.jar --output ./bin/vulnz.jar
      - run: java -jar ./bin/vulnz.jar cve --cache --directory ./nvdcve-data --debug
      - run: mkdir -p ./build/db
      - run: curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.4/dependency-check-9.0.4-release.zip --output ./build/dependency-check.zip
      - run: cd ./build && unzip dependency-check.zip && cd ..
      - run: ./build/dependency-check/bin/dependency-check.sh --updateonly --nvdDatafeed file://$PWD/nvdcve-data/nvdcve-{0}.json.gz --data ./build/db

  update-nvd-data:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: git config user.name fizzpod-machine-user
      - run: git config user.email fizzpod-machine-user@users.noreply.github.com
      - run: mkdir -p ./bin && curl -L https://github.com/jeremylong/Open-Vulnerability-Project/releases/download/v5.1.0/vulnz-5.1.0.jar --output ./bin/vulnz.jar
      - run: java -jar ./bin/vulnz.jar cve --cache --directory ./nvdcve-data --debug
      - run: version=$(date +'%Y.%m.%d') && git add -A && git commit -m "$version CVE NVD Data Updated" && git tag "$version" 
      - run: version=$(date +'%Y.%m.%d') && git push --atomic --set-upstream origin $CIRCLE_BRANCH $version
      
  publish:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: echo "publish"
      - run: mkdir -p ./build/db
      - run: curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.4/dependency-check-9.0.4-release.zip --output ./build/dependency-check.zip
      - run: cd ./build && unzip dependency-check.zip && cd ..
      - run: ./build/dependency-check/bin/dependency-check.sh --updateonly --nvdDatafeed file://$PWD/nvdcve-data/nvdcve-{0}.json.gz --data ./build/db

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - update-nvd-data:
          context: boxhead-builds
          filters:
            branches:
              only: /^(?:main|master)$/
      - publish:
          context: boxhead-builds
          filters:
            # only act on version tags
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
